### ISSUE TITLE
build error with git version 7924f67baccc137666272a6121738135217acc92

### ISSUE THREAD

**Issue by charlescui** [openzipkin/zipkin-ui#31] opened 2017-03-22 13:29 UTC
zipkin-ui build error with git version [7924f67bac](https://github.com/openzipkin/zipkin-js/commit/7924f67baccc137666272a6121738135217acc92)

when I git clone the master code, I do below:

1. npm install
2. npm run build

in the second step, console show errors with compile.

```shell
➜  zipkin-ui git:(master) npm run build

> zipkin-ui@0.1.0 build /Users/cuizheng/Documents/Code/charlescui.git/zipkin-ui
> gulp build

[20:11:34] Using gulpfile ~/Documents/Code/charlescui.git/zipkin-ui/gulpfile.js
[20:11:34] Starting 'build'...
/Users/cuizheng/Documents/Code/charlescui.git/zipkin-ui/node_modules/extract-text-webpack-plugin/index.js:184
		throw new Error("Breaking change: extract now only takes a single argument. Either an options " +
		^

Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
Example: if your old code looked like this:
    ExtractTextPlugin.extract('style-loader', 'css-loader')

You would change it to:
    ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })

The available options are:
    use: string | object | loader[]
    fallback: string | object | loader[]
    publicPath: string

    at Function.ExtractTextPlugin.extract (/Users/cuizheng/Documents/Code/charlescui.git/zipkin-ui/node_modules/extract-text-webpack-plugin/index.js:184:9)
    at Object.<anonymous> (/Users/cuizheng/Documents/Code/charlescui.git/zipkin-ui/config/webpack.common.js:34:43)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/cuizheng/Documents/Code/charlescui.git/zipkin-ui/config/webpack.prod.js:4:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
[20:11:35] 'build' errored after 750 ms
[20:11:35] Error in plugin 'gulp-shell'
Message:
    Command `webpack --config config/webpack.prod.js --progress --colors --profile --bail` failed with exit code 1

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/cuizheng/Documents/Code/nvm/versions/node/v7.2.0/bin/node" "/Users/cuizheng/Documents/Code/nvm/versions/node/v7.2.0/bin/npm" "run" "build"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! zipkin-ui@0.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zipkin-ui@0.1.0 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zipkin-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zipkin-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zipkin-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cuizheng/Documents/Code/charlescui.git/zipkin-ui/npm-debug.log
```

I fixed the error and go on build, come on with other error.
So I fixed all errors with current version code, and modify the below file.

```
[main] aaa2b99e8246abe975e6f47a9e8814ffef6db101 - commit 1 of 110                                                          10%
commit aaa2b99e8246abe975e6f47a9e8814ffef6db101
Refs: [master], {origin/master}, {origin/HEAD}, 0.0.1-4-gaaa2b99
Author:     崔峥
AuthorDate: Wed Mar 22 20:30:14 2017 +0800
Commit:     崔峥
CommitDate: Wed Mar 22 20:30:14 2017 +0800

    fix 'npm run build' error
---
 config/webpack.common.js | 16 +++++++++++-----
 config/webpack.prod.js   | 15 ++++++++++-----
 package.json             |  7 +++++--

```

then compile success in the folder `target/classes/zipkin-ui/`

**Comment by devinsba** [comment] 2017-03-22 15:50
Duplicate of #29

**Closed by devinsba** 2017-03-22 15:50 UTC
